# lightning.pytorch==2.1.1
seed_everything: 697995365
trainer:
  accelerator: auto
  strategy: ddp_find_unused_parameters_true
  devices: 4
  num_nodes: 1
  precision: 32
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: /data/scratch/bty174/lightning_logs
      name: 90-10
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: epoch={epoch}-steps={steps}-train_loss={val/loss:.2f}
      monitor: train/loss
      verbose: false
      save_last: null
      save_top_k: -1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: false
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: 1
      save_on_train_epoch_end: null
      enable_version_counter: true
  - class_path: eft.data.MemoryLoggingCallback
    init_args: {}
  fast_dev_run: false
  max_epochs: 20
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 1
  enable_checkpointing: true
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 64
  gradient_clip_val: 0.5
  gradient_clip_algorithm: null
  deterministic: true
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: auto
model:
  pretrained_state_dict: null
  learning_rate: 1.0e-05
data:
  data_dir: data/sequences
  batch_size: 4
  num_workers: 0
  dev: false
ckpt_path: null
